### ISSUE TITLE
aggregate() API does not match promised-mongo/mongo

### ISSUE THREAD

**Issue by yangchristian** [CrossLead/temporal-mongo#4]
Per PR #3, @bsouthga caught fact that our `aggregate()` API is non-standard. @mcgrit can you take an initial look?

**Comment by bsouthga** [comment]
Potential fix in #5 https://github.com/CrossLead/temporal-mongo/commit/1f59ec117d60ceb3afad35f984caba62d20a7d02

**Comment by bsouthga** [comment]
fixed in https://github.com/CrossLead/temporal-mongo/commit/9a59ed0ae132a10ad5d1269d550812e02d06da80
